---
- hosts: ticket_server
  vars:
    php_memory_limit: "128M"
    php_max_execution_time: "90"
    php_upload_max_filesize: "256M"
    php_packages:
      - php
      - php-cli
      - php-common
      - php-devel
      - php-gd
      - php-mbstring
      - php-pdo
      - php-pecl-apc
      - php-xml

    apache_listen_port: 80
    apache_create_vhosts: True

    ntp_timezone: America/Toronto
    newrelic_service_state: started
    newrelic_license_key: 9224a8818f464f228eb1c32f1e6858e56ddac037

    mysql_root_password: welcome
    mysql_packages:
      - mariadb
      - mariadb-server
      - mariadb-libs
      - MySQL-python
      - perl-DBD-MySQL
    mysql_daemon: mariadb
    mysql_log_error: /var/log/mariadb/mariadb.log
    mysql_syslog_tag: mariadb
    mysql_pid_file: /var/run/mariadb/mariadb.pid

  pre_tasks:
    - name: Install Common Packages
      yum: name={{ item }} state=installed
      with_items:
        - epel-release
        - firewalld
        - firewall-config

    - name: Validate firewalld service is operational
      service: name=firewalld state=started enabled=yes

  roles:
    - { role: franklinkim.newrelic }
    - { role: kuon.firewalld, port: 22, public: true }
    - { role: kuon.firewalld, port: 80, public: true }
    - { role: geerlingguy.ntp }
    - { role: geerlingguy.git }
    - { role: geerlingguy.php }
    - { role: geerlingguy.apache }
    - { role: geerlingguy.mysql }

